name: Docker Image CI
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
jobs:
    build-linux:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Build Linux Docker image
          run: docker build linux --file linux/Dockerfile --tag sorcerer86pt/vs6noble:${{ github.sha }}
    build-windows:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v4
        - name: Build Windows Docker image
          run: docker build servercore --file servercore/Dockerfile --tag sorcerer86pt/vc6servercore:${{ github.sha }}
          shell: powershell