name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Linux Docker image
        run: |
          docker build -t sorcerer86pt/vs6noble:${{ github.sha }} -f linux/Dockerfile linux

      - name: Push Docker image to Docker Hub
        uses: timo-reymann/dockerhub-semantic-release-gh-action@v1
        with:
          image: sorcerer86pt/vs6noble
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          github_token: ${{ secrets.PAT }}
          platforms: linux/amd64,linux/arm64
